# Базовая инфраструктура
# Для локальной разработки

services:
  postgres:
    container_name: local-postgresql
    image: postgres:15-alpine
    restart: unless-stopped
    # если Postgresql уже установлен локально, используй другой порт на хост-машине (например "5433:5432")
    # если меняется порт, не забудь изменить его в DB_URL внутри локального .env или ./config/fonfig.dev.yml
    ports:
      - "5432:5432"
    volumes:
      - local-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=linka
      - POSTGRES_PASSWORD=linka
      - POSTGRES_DB=linka
    networks:
      - linka-net
    healthcheck:
      # Без доп. ключей. В хелсчеке утилита pg_isready по умолчанию использует дефолтные креды к БД
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  minio:
    container_name: local-minio
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000" # порт API
      - "9001:9001" # порт веб-консоли
    volumes:
      - local-minio-volume:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    networks:
      - linka-net
    healthcheck:
      # mc ready local — встроенная утилита проверки готовности дисков MinIO
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # запуск сервера MinIO с указанием папки для данных и порта веб-консоли
    command: [ "server", "/data", "--console-address", ":9001" ]

  nats:
    container_name: local-nats
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "4222:4222" # порт приложения
      - "8222:8222" # порт мониторинга
    volumes:
      - local-nats-volume:/data
    networks:
      - linka-net
    healthcheck:
      # wget встроен в alpine образ NATS по умолчанию, проверяет эндпоинт мониторинга
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:8222/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # js включает JetStream, -m включает мониторинг, --sd задает папку хранения сообщений
    command: [ "-js", "-m", "8222", "--sd", "/data" ]

  loki:
    image: grafana/loki:3.7.0
    container_name: local-loki
    ports:
      - "3100:3100"
    volumes:
      - local-loki-volume:/loki
      - ./deploy/loki/loki-config.yml:/etc/loki/config.yml
    networks:
      - linka-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    command: -config.file=/etc/loki/config.yml

  alloy:
    image: grafana/alloy:v1.17.0
    container_name: local-alloy
    volumes:
      - ./deploy/alloy/alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - local-alloy-volume:/var/lib/alloy/data
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - linka-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/12345"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  redis:
    container_name: local-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - local-redis-volume:/data
    networks:
      - linka-net
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  local-postgres-volume:
  local-minio-volume:
  local-nats-volume:
  local-loki-volume:
  local-alloy-volume:
  local-redis-volume:


networks:
  linka-net:
