// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_repo_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	v5 "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockauthRepoIface is a mock of authRepoIface interface.
type MockauthRepoIface struct {
	ctrl     *gomock.Controller
	recorder *MockauthRepoIfaceMockRecorder
	isgomock struct{}
}

// MockauthRepoIfaceMockRecorder is the mock recorder for MockauthRepoIface.
type MockauthRepoIfaceMockRecorder struct {
	mock *MockauthRepoIface
}

// NewMockauthRepoIface creates a new mock instance.
func NewMockauthRepoIface(ctrl *gomock.Controller) *MockauthRepoIface {
	mock := &MockauthRepoIface{ctrl: ctrl}
	mock.recorder = &MockauthRepoIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthRepoIface) EXPECT() *MockauthRepoIfaceMockRecorder {
	return m.recorder
}

// beginTx mocks base method.
func (m *MockauthRepoIface) beginTx(ctx context.Context) (v5.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "beginTx", ctx)
	ret0, _ := ret[0].(v5.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// beginTx indicates an expected call of beginTx.
func (mr *MockauthRepoIfaceMockRecorder) beginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "beginTx", reflect.TypeOf((*MockauthRepoIface)(nil).beginTx), ctx)
}

// getUserContactForResend mocks base method.
func (m *MockauthRepoIface) getUserContactForResend(ctx context.Context, userID uuid.UUID) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getUserContactForResend", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// getUserContactForResend indicates an expected call of getUserContactForResend.
func (mr *MockauthRepoIfaceMockRecorder) getUserContactForResend(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getUserContactForResend", reflect.TypeOf((*MockauthRepoIface)(nil).getUserContactForResend), ctx, userID)
}

// rotateEmailTokens mocks base method.
func (m *MockauthRepoIface) rotateEmailTokens(ctx context.Context, tokenID, userID uuid.UUID, hash []byte, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "rotateEmailTokens", ctx, tokenID, userID, hash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// rotateEmailTokens indicates an expected call of rotateEmailTokens.
func (mr *MockauthRepoIfaceMockRecorder) rotateEmailTokens(ctx, tokenID, userID, hash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "rotateEmailTokens", reflect.TypeOf((*MockauthRepoIface)(nil).rotateEmailTokens), ctx, tokenID, userID, hash, expiresAt)
}

// useEmailVerifyToken mocks base method.
func (m *MockauthRepoIface) useEmailVerifyToken(ctx context.Context, token []byte) (uuid.UUID, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "useEmailVerifyToken", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// useEmailVerifyToken indicates an expected call of useEmailVerifyToken.
func (mr *MockauthRepoIfaceMockRecorder) useEmailVerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "useEmailVerifyToken", reflect.TypeOf((*MockauthRepoIface)(nil).useEmailVerifyToken), ctx, token)
}

// verifyStudent mocks base method.
func (m *MockauthRepoIface) verifyStudent(ctx context.Context, studentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyStudent", ctx, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyStudent indicates an expected call of verifyStudent.
func (mr *MockauthRepoIfaceMockRecorder) verifyStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyStudent", reflect.TypeOf((*MockauthRepoIface)(nil).verifyStudent), ctx, studentID)
}

// verifyUser mocks base method.
func (m *MockauthRepoIface) verifyUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyUser indicates an expected call of verifyUser.
func (mr *MockauthRepoIfaceMockRecorder) verifyUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyUser", reflect.TypeOf((*MockauthRepoIface)(nil).verifyUser), ctx, userID)
}

// withTx mocks base method.
func (m *MockauthRepoIface) withTx(tx v5.Tx) authRepoIface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withTx", tx)
	ret0, _ := ret[0].(authRepoIface)
	return ret0
}

// withTx indicates an expected call of withTx.
func (mr *MockauthRepoIfaceMockRecorder) withTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withTx", reflect.TypeOf((*MockauthRepoIface)(nil).withTx), tx)
}
